### ISSUE TITLE
とても消極的にRuboCopを推奨したい

### ISSUE THREAD

**Issue by universato** [universato/ac-library-rb#7]
Rubyには、コードのスタイルをチェックや自動修正してくれるRuboCopというgemがあります。

レポジトリ全体でスタイルが強制されていた方が、書いたり読みやすかったりすることも多いと思います。
一方で、デフォルトで様々な点について修正を要求してくるため、嫌う人は嫌っています。
また、PRは気軽に送って欲しいという気持ちやスタイルを強制させたくないという気持ちもあり、慎重になっています。

他に、RuboCopを使える人が自動修正すればいいと考える一方で、自分が読みやすいと思って書いたコードを自動的に修正されたくないこともあると考えてます。

問題点が整理できてないのですが、
「みんなにも強制させたいスタイル」や「好きにさせて欲しいスタイル」があったら教えて欲しいです！

自分は、インデントの幅2は、基本的に強制させたいです。
一方で、文字列のリテラルはシングルクォートでもダブルクォートでもどちらでも良いと思っています。

絶対的にRuboCopのデフォルトルールを推奨するわけではないですが、使ってみていいなと思うこともあると思うのでPRを送って下さる向けにその旨をREADMEに書かなければと考えています。

**Comment by kotatsugame** [comment]
僕には特にこだわりのスタイルはないです。

**Comment by 9sako6** [comment]
インデントの幅2は同意です。あとは変数名、メソッド名のスネークケースを望むくらいです。
使いたい方向けに記述を添えるのはいい案だと思いました。

運用においては、RuboCop のバージョン違いがないように `Gemfile` で管理するのはありかなと思いました。（私の方で PR は用意できます）

**Comment by universato** [comment]
@kotatsugame 
こたつがめさんにそう言って貰えるとありがたいです！

こういうコード`a.each { |a| puts a }`だと(ブロックの外と中で同じ変数名を使っているケース)、ブロックが短ければわかりやすいとは思うものの、RuboCopで1段階上の警告がでるし意味合いが変わるので変更した方が良いのかもしれないと考えていました。

@9sako6
そうですね。変数名・メソッド名、クラス名、定数など、一般的な形の方がよいですね。
あとは、(好みもあるけど)RuboCopに自動修正してもらう観点から、+などの記号の前後、カンマの後にスペースは必要かなと思ってます。結局は修正されるだろうと。
`Geimfile`を使える人が使えるようにするのはありだと思います！

**Comment by kotatsugame** [comment]
> `a.each { |a| puts a }`

これダメなんですね……。変数名に迷っているだけなので、修正されるならいいと思います。演算子の前後のスペースもあんまり入れていませんでしたね。
どういう形で修正が行われるのかよくわかっていませんが、このリポジトリに標準の設定ファイルが用意されるなら、手元にRuboCopを用意して直してプルリクを送る気概はあります。

**Comment by hkdnet** [comment]
> こういうコードa.each { |a| puts a }だと(ブロックの外と中で同じ変数名を使っているケース)

これはもともと Ruby 本体の警告として出ていたものでしたが、[2.5 -> 2.6 の変更時に警告が削除されました](https://bugs.ruby-lang.org/issues/12490)

```
$ ruby -we 'puts RUBY_VERSION; a = 1; [1,2,3].each{|a| a}'
-e:1: warning: shadowing outer local variable - a
2.5.3

$ ruby -we 'puts RUBY_VERSION; a = 1; [1,2,3].each{|a| a}'
2.6.6
```

該当 cop のドキュメントにも 2.6 より前のバージョンの警告を真似しているという旨が記載されています。
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Lint/ShadowingOuterLocalVariable

> This mirrors the warning given by `ruby -cw` prior to Ruby 2.6: “shadowing outer local variable - foo”.


なので 2.7 準拠のこのリポジトリではこの cop は disable されるべきだと思っています。
（が、僕自身はまだコード書いてもないのでご参考程度に、ということで）

**Comment by universato** [comment]
@hkdnet 
ありがとうございます！
Ruby本体の警告が削除されたときのやりとり面白いですね。
「自分は良いと思うけど、Matzは悪い慣習だと考えているから、説得してくれ」みたいな。
ここのやりとりで提示されている「ブロックの外と中で同じ変数名を使いたいケース」は興味深かったです。なるほど、という感じでした。

**Comment by universato** [comment]
RuboCopのデフォルトから緩めたい設定を書いてたのですが多すぎて、まだ途中なのですが別のことやろうと思ったので、途中のものをアップします。デフォルトから緩めているだけです。RuboCopの設定をあまりしたことがなくてよくわかってないです。たぶんRuboCopは最新のバージョンを使っています。

```yaml
AllCops:
  NewCops: enable
# デフォルトだとメソッドの開始ブロックの手前にスペースを要求してくるが、競プロ界隈では一般的ではないと思う。
Layout/SpaceBeforeBlockBraces:
  Enabled: false
# デフォルトだと(0..10)を推奨してくるが、(0 .. 10)の方が見やすい気がするので許したい。
Layout/SpaceInsideRangeLiteral:
  Enabled: false
# 何でもかんでも変数名を1文字にするのはよくないと思うが、本家ACLでも1文字を使っているし、競プロではn, x, y, i, j など1文字の変数名は慣習的によく使われている。
Naming/MethodParameterName:
  Enabled: false
# x == 0のとき、x.zero?を推奨してくるが、少なくとも競プロではx == 0が一般的で読みやすいはず。zero?はRuby特有の表現でも逆に読みにくいかも。
Style/NumericPredicate:
  Enabled: false
# 競プロ界隈では、多重代入はみんな使っていてわかりやすいみたいだから、制限があると困る。
Style/ParallelAssignment:
  Enabled: false
# 拡張子がついてる方が作ったファイルとわかりやすい気がしたから、.rbをつけることを許したい
Style/RedundantFileExtensionInRequire:
  Enabled: false
# Crystalに合わせたいみたい、多様性の尊重(?)により、文字列はダブルクォートでもシングルクォートでもどちらも良いとしたい。
Style/StringLiterals:
  Enabled: false
# メソッドの複雑さの数値。代入の回数が増えたりして、複雑になると警告をだす。緩める。
Metrics/AbcSize:
  Max: 334
# デフォルトはメソッドの中が10行超えると警告だが厳しすぎる。行数よりも速さが大事だと思うので、行数を減らすの大変そうで労力に合わなそうな気がする。
Metrics/MethodLength:
  Max: 334
```
